### PR TITLE
Fix/gcc5.4 tuple init list

### PR DESCRIPTION
**Pull request by williamleong**
Fix error converting to std::tuple from initializer list would use explicit constructor error in GCC5.4.

### CODE REVIEW

**Comment by aaron-michaux** [comment]
I appreciate that you want to use this on older compilers, but I want to keep the code as clean and straightforward as possible. It's C++17.

It should work in Visual C++ 2017 or 2019.

**Comment by williamleong** [comment]
I have a different requirement but I totally understand where you are coming from, I would have preferred to do it your way if I didn't need to support an older compiler. Thanks!

**Comment by aaron-michaux** [comment]
Hi, I merged your pull request in the end. Can you check it works on
MSVC2015? Thanks in advance.

**Comment by williamleong** [comment]
Works good, thanks!

**Pull request closed without merging**
